# Generated by Django 2.2.5 on 2019-10-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Book author_name')),
                ('about_author', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Book author_name',
                'verbose_name_plural': 'Books authors',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book category')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book name')),
                ('price', models.CharField(max_length=200, verbose_name='Book price')),
                ('publisher', models.CharField(max_length=100, verbose_name='Book publisher')),
                ('description', models.TextField()),
                ('isbn', models.BigIntegerField(verbose_name='Book ISBN')),
                ('rate', models.IntegerField(default=0, verbose_name='Book rating')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Book added')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='media/%Y%m%d%h/cover', verbose_name='Book cover')),
                ('available', models.BooleanField(default=True, verbose_name='Book available')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Book Slug')),
                ('img_source', models.URLField(max_length=255)),
                ('book_source', models.URLField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='store.BookAuthor', verbose_name='Book author')),
                ('category', models.ManyToManyField(related_name='category', to='store.BookCategory', verbose_name='book category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent', models.DateTimeField(auto_now_add=True, verbose_name='Sent')),
            ],
            options={
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'Contact requests',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Author name')),
                ('review', models.TextField(verbose_name='Book review')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='Review added')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='store.BookModel', verbose_name='Book')),
            ],
        ),
    ]
