# Generated by Django 2.2.5 on 2019-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191022_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_source',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='img_source',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
